### ISSUE TITLE
Modify list output with '\n'

### ISSUE THREAD

**Issue by gmyuval** [CommaSword/fugazi#4]
Currently list command returns a comma separated string.
To improve readability the operation should return a list separated by newlines

**Comment by amir-arad** [comment]
we can duplicate the way mongo connector displays a list of DBs
https://github.com/fugazi-io/connector.node.mongo/blob/master/scripts/src/databases.ts#L38

**Comment by Omerss** [comment]
This issue is also important for displaying the log file

**Comment by amir-arad** [comment]
moved to CommaSword/Daedalus#6
